<?php
/**
 * Created by PhpStorm.
 * User: yannick.dieng
 * Date: 19/04/2017
 * Time: 15:20
 */

namespace AppBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class StudyType extends AbstractType{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
//        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $days = array(  "Lundi" => "Lundi",
                        "Mardi" => "Mardi",
                        "Mercredi" => "Mercredi",
                        "Jeudi" => "Jeudi",
                        "Vendredi" => "Vendredi",
                        "Samedi" => "Samedi",
                        "Dimanche" => "Dimanche");

        $builder->add('title', TextType::class)
            ->add('day', ChoiceType::class, array(
                                                    'choices' => $days,
                                                    'multiple' => false)
            )
            ->add('statTime', TimeType::class, array(
                                                        'input' => 'datetime',
                                                        'widget' => 'choice')
            )
            ->add('endTime', TimeType::class, array(
                                                        'input' => 'datetime',
                                                        'widget' => 'choice')
            )
            ->add('address')
            ->add('levels')
            ->add('save', ButtonType::class);
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => Study::class
        ));
    }
}
